import assert from 'node:assert/strict';
import test from 'node:test';
import { aliexpressProductId, metadataFromAliExpressProduct, resolveAliExpressAffiliateProduct } from '../scripts/aliexpress-link-resolver.mjs';

test('extracts an AliExpress product id from an attributed destination URL', () => {
  assert.equal(aliexpressProductId('https://www.aliexpress.com/item/1005011620902362.html?aff_fsk=example'), '1005011620902362');
});

test('converts affiliate API product data into publishable metadata', () => {
  assert.deepEqual(metadataFromAliExpressProduct({
    product_title: 'Auriculares inalámbricos con cancelación de ruido',
    product_main_image_url: 'https://example.test/image.jpg',
    target_sale_price: '19.99',
    target_original_price: '39.99',
  }), {
    title: 'Auriculares inalámbricos con cancelación de ruido',
    description: 'Auriculares inalámbricos con cancelación de ruido',
    imageUrl: 'https://example.test/image.jpg',
    price: 19.99,
    previousPrice: 39.99,
  });
});

test('resolves a short AliExpress URL and returns the link generated by the affiliate API', async () => {
  const shortUrl = 'https://s.click.aliexpress.com/e/_example';
  const metadata = await resolveAliExpressAffiliateProduct(shortUrl, {
    appKey: 'test-key',
    appSecret: 'test-secret',
    trackingId: 'chollosaldia88id',
  }, {
    fetchImpl: async (url) => {
      if (url === shortUrl) {
        return { url: 'https://www.aliexpress.com/item/1005011620902362.html?source=short' };
      }
      return {
        json: async () => ({
          aliexpress_affiliate_product_query_response: {
            resp_result: {
              result: {
                products: {
                  product: [{
                    product_title: 'Ventilador silencioso 40 W',
                    product_main_image_url: 'https://example.test/fan.jpg',
                    target_sale_price: '17.78',
                    target_original_price: '29.99',
                    promotion_link: 'https://s.click.aliexpress.com/e/_tu-enlace',
                  }],
                },
              },
            },
          },
        }),
      };
    },
  });
  assert.equal(metadata.title, 'Ventilador silencioso 40 W');
  assert.equal(metadata.price, 17.78);
  assert.equal(metadata.productId, '1005011620902362');
  assert.equal(metadata.affiliateUrl, 'https://s.click.aliexpress.com/e/_tu-enlace');
});
