import assert from 'node:assert/strict';
import test from 'node:test';
import { aliexpressProductId, metadataFromAliExpressHtml, metadataFromAliExpressProduct, resolveAliExpressAffiliateProduct, resolveAliExpressProductUrl } from '../scripts/aliexpress-link-resolver.mjs';

test('extracts an AliExpress product id from an attributed destination URL', () => {
  assert.equal(aliexpressProductId('https://www.aliexpress.com/item/1005011620902362.html?aff_fsk=example'), '1005011620902362');
});

test('converts affiliate API product data into publishable metadata', () => {
  assert.deepEqual(metadataFromAliExpressProduct({
    product_title: 'Auriculares inalámbricos con cancelación de ruido',
    product_main_image_url: 'https://example.test/image.jpg',
    target_sale_price: '19.99',
    target_original_price: '39.99',
  }), {
    title: 'Auriculares inalámbricos con cancelación de ruido',
    description: 'Auriculares inalámbricos con cancelación de ruido',
    imageUrl: 'https://example.test/image.jpg',
    price: 19.99,
    previousPrice: 39.99,
  });
});

test('resolves a short AliExpress URL and returns the link generated by the affiliate API', async () => {
  const shortUrl = 'https://s.click.aliexpress.com/e/_example';
  const canonicalUrl = 'https://es.aliexpress.com/item/1005011620902362.html';
  const metadata = await resolveAliExpressAffiliateProduct(shortUrl, {
    appKey: 'test-key',
    appSecret: 'test-secret',
    trackingId: 'chollosaldia88id',
  }, {
    resolveShortUrl: async () => canonicalUrl,
    fetchImpl: async (url) => {
      if (url === canonicalUrl) {
        return {
          ok: true,
          url: canonicalUrl,
          text: async () => '<meta property="og:title" content="Ventilador silencioso 40 W"><meta property="og:image" content="https://example.test/fan.jpg">',
        };
      }
      const method = new URL(url).searchParams.get('method');
      if (method === 'aliexpress.affiliate.productdetail.get') return {
        ok: true,
        json: async () => ({
          aliexpress_affiliate_productdetail_get_response: {
            resp_result: {
              result: {
                products: {
                  product: [{
                    product_id: '1005011620902362',
                    product_title: 'Ventilador silencioso 40 W',
                    product_main_image_url: 'https://example.test/fan.jpg',
                    target_sale_price: '17.78',
                    target_original_price: '29.99',
                  }],
                },
              },
            },
          },
        }),
      };
      assert.equal(method, 'aliexpress.affiliate.link.generate');
      return {
        ok: true,
        json: async () => ({
          aliexpress_affiliate_link_generate_response: {
            resp_result: { result: { promotion_links: { promotion_link: [{
              source_value: canonicalUrl,
              promotion_link: 'http://s.click.aliexpress.com/e/_tu-enlace',
            }] } } },
          },
        }),
      };
    },
  });
  assert.equal(metadata.title, 'Ventilador silencioso 40 W');
  assert.equal(metadata.price, 17.78);
  assert.equal(metadata.productId, '1005011620902362');
  assert.equal(metadata.affiliateUrl, 'https://s.click.aliexpress.com/e/_tu-enlace');
  assert.equal(metadata.identityVerified, true);
});

test('uses the redirect fallback when GitHub fetch cannot open a short AliExpress link', async () => {
  const shortUrl = 'https://s.click.aliexpress.com/e/_blocked';
  const canonicalUrl = 'https://es.aliexpress.com/item/1005008265378976.html';
  const metadata = await resolveAliExpressAffiliateProduct(shortUrl, {
    appKey: 'test-key',
    appSecret: 'test-secret',
    trackingId: 'chollosaldia88id',
  }, {
    fetchImpl: async (url) => {
      if (url === shortUrl) throw new Error('fetch failed');
      if (url === canonicalUrl) return { ok: true, url: canonicalUrl, text: async () => '' };
      const method = new URL(url).searchParams.get('method');
      if (method === 'aliexpress.affiliate.productdetail.get') return {
        ok: true,
        json: async () => ({
          aliexpress_affiliate_productdetail_get_response: {
            resp_result: { result: { products: { product: [{
              product_id: '1005008265378976',
              product_title: 'Producto recuperado desde enlace corto',
              product_main_image_url: 'https://example.test/product.jpg',
              target_sale_price: '18.90',
              promotion_link: 'https://s.click.aliexpress.com/e/_propio',
            }] } } },
          },
        }),
      };
      return {
        ok: true,
        json: async () => ({
          aliexpress_affiliate_link_generate_response: {
            resp_result: { result: { promotion_links: { promotion_link: [{
              promotion_link: 'https://s.click.aliexpress.com/e/_propio',
              source_value: canonicalUrl,
            }] } } },
          },
        }),
      };
    },
    resolveShortUrl: async () => canonicalUrl,
  });
  assert.equal(metadata.productId, '1005008265378976');
  assert.equal(metadata.affiliateUrl, 'https://s.click.aliexpress.com/e/_propio');
});

test('prefers the real curl destination over a generic fetch redirect for an AliExpress short link', async () => {
  const canonical = await resolveAliExpressProductUrl('https://a.aliexpress.com/_perfume', {
    fetchImpl: async (url) => ({
      url: String(url).includes('3256812534770464')
        ? 'https://es.aliexpress.com/item/1005012721085216.html'
        : 'https://es.aliexpress.com/item/3256812534770464.html',
      text: async () => '',
    }),
    execFileImpl: async () => ({ stdout: 'https://es.aliexpress.com/item/3256812534770464.html' }),
  });
  assert.equal(canonical, 'https://es.aliexpress.com/item/1005012721085216.html');
});

test('ignores stale catalogue facts but still converts the exact canonical URL to this affiliate', async () => {
  const canonicalUrl = 'https://es.aliexpress.com/item/1005012721085216.html';
  const metadata = await resolveAliExpressAffiliateProduct('https://a.aliexpress.com/_perfume', {
    appKey: 'test-key',
    appSecret: 'test-secret',
    trackingId: 'chollosaldia88id',
  }, {
    resolveShortUrl: async () => canonicalUrl,
    fetchImpl: async (url) => {
      if (url === canonicalUrl) return {
        ok: true,
        url: canonicalUrl,
        text: async () => String.raw`\u003cmeta property=\"og:title\" content=\"Maison Alhambra Jean Lowe Fantasme Eau de Parfum - AliExpress 66\" /\u003e \u003cmeta property=\"og:image\" content=\"https://ae01.alicdn.com/kf/perfume.jpg\" /\u003e`,
      };
      const method = new URL(url).searchParams.get('method');
      if (method === 'aliexpress.affiliate.productdetail.get') return {
        ok: true,
        json: async () => ({
          aliexpress_affiliate_productdetail_get_response: { resp_result: { result: { products: { product: [{
            product_id: '1005012646899284',
            product_title: 'Humidificador que no corresponde',
            target_sale_price: '19.99',
            promotion_link: 'https://s.click.aliexpress.com/e/_producto-incorrecto',
          }] } } } },
        }),
      };
      return {
        ok: true,
        json: async () => ({
          aliexpress_affiliate_link_generate_response: { resp_result: { result: { promotion_links: { promotion_link: [{
            source_value: canonicalUrl,
            promotion_link: 'https://s.click.aliexpress.com/e/_perfume-propio',
          }] } } } },
        }),
      };
    },
  });
  assert.equal(metadata.canonicalUrl, canonicalUrl);
  assert.equal(metadata.productId, '1005012721085216');
  assert.equal(metadata.title, 'Maison Alhambra Jean Lowe Fantasme Eau de Parfum');
  assert.equal(metadata.imageUrl, 'https://ae01.alicdn.com/kf/perfume.jpg');
  assert.equal(metadata.price, undefined);
  assert.equal(metadata.affiliateUrl, 'https://s.click.aliexpress.com/e/_perfume-propio');
  assert.equal(metadata.identityVerified, false);
});

test('reads AliExpress title and photo from its escaped social metadata', () => {
  const metadata = metadataFromAliExpressHtml(String.raw`\u003cmeta property=\"og:title\" content=\"Perfume unisex 100 ml - AliExpress 66\" /\u003e\u003cmeta property=\"og:image\" content=\"https://ae01.alicdn.com/kf/perfume.jpg\" /\u003e\u003cmeta property=\"al:android:url\" content=\"aliexpress://product/detail?productId=1005012721085216\u0026source=test\" /\u003e`);
  assert.equal(metadata.title, 'Perfume unisex 100 ml');
  assert.equal(metadata.imageUrl, 'https://ae01.alicdn.com/kf/perfume.jpg');
  assert.equal(metadata.productId, '1005012721085216');
});
