import assert from 'node:assert/strict';
import test from 'node:test';
import { aliexpressProductId, metadataFromAliExpressProduct, resolveAliExpressAffiliateProduct, resolveAliExpressProductUrl } from '../scripts/aliexpress-link-resolver.mjs';

test('extracts an AliExpress product id from an attributed destination URL', () => {
  assert.equal(aliexpressProductId('https://www.aliexpress.com/item/1005011620902362.html?aff_fsk=example'), '1005011620902362');
});

test('converts affiliate API product data into publishable metadata', () => {
  assert.deepEqual(metadataFromAliExpressProduct({
    product_title: 'Auriculares inalámbricos con cancelación de ruido',
    product_main_image_url: 'https://example.test/image.jpg',
    target_sale_price: '19.99',
    target_original_price: '39.99',
  }), {
    title: 'Auriculares inalámbricos con cancelación de ruido',
    description: 'Auriculares inalámbricos con cancelación de ruido',
    imageUrl: 'https://example.test/image.jpg',
    price: 19.99,
    previousPrice: 39.99,
  });
});

test('resolves a short AliExpress URL and returns the link generated by the affiliate API', async () => {
  const shortUrl = 'https://s.click.aliexpress.com/e/_example';
  const metadata = await resolveAliExpressAffiliateProduct(shortUrl, {
    appKey: 'test-key',
    appSecret: 'test-secret',
    trackingId: 'chollosaldia88id',
  }, {
    fetchImpl: async (url) => {
      if (url === shortUrl) {
        return { url: 'https://www.aliexpress.com/item/1005011620902362.html?source=short' };
      }
      return {
        json: async () => ({
          aliexpress_affiliate_product_query_response: {
            resp_result: {
              result: {
                products: {
                  product: [{
                    product_title: 'Ventilador silencioso 40 W',
                    product_main_image_url: 'https://example.test/fan.jpg',
                    target_sale_price: '17.78',
                    target_original_price: '29.99',
                    promotion_link: 'https://s.click.aliexpress.com/e/_tu-enlace',
                  }],
                },
              },
            },
          },
        }),
      };
    },
  });
  assert.equal(metadata.title, 'Ventilador silencioso 40 W');
  assert.equal(metadata.price, 17.78);
  assert.equal(metadata.productId, '1005011620902362');
  assert.equal(metadata.affiliateUrl, 'https://s.click.aliexpress.com/e/_tu-enlace');
});

test('uses the redirect fallback when GitHub fetch cannot open a short AliExpress link', async () => {
  const shortUrl = 'https://s.click.aliexpress.com/e/_blocked';
  const metadata = await resolveAliExpressAffiliateProduct(shortUrl, {
    appKey: 'test-key',
    appSecret: 'test-secret',
    trackingId: 'chollosaldia88id',
  }, {
    fetchImpl: async (url) => {
      if (url === shortUrl) throw new Error('fetch failed');
      return {
        json: async () => ({
          aliexpress_affiliate_product_query_response: {
            resp_result: { result: { products: { product: [{
              product_id: '1005008265378976',
              product_title: 'Producto recuperado desde enlace corto',
              product_main_image_url: 'https://example.test/product.jpg',
              target_sale_price: '18.90',
              promotion_link: 'https://s.click.aliexpress.com/e/_propio',
            }] } } },
          },
        }),
      };
    },
    resolveShortUrl: async () => 'https://es.aliexpress.com/item/1005008265378976.html?from=short',
  });
  assert.equal(metadata.productId, '1005008265378976');
});

test('prefers the real curl destination over a generic fetch redirect for an AliExpress short link', async () => {
  const canonical = await resolveAliExpressProductUrl('https://a.aliexpress.com/_perfume', {
    fetchImpl: async () => ({ url: 'https://es.aliexpress.com/item/3256812534770464.html' }),
    execFileImpl: async () => ({ stdout: 'https://es.aliexpress.com/item/1005012721085216.html' }),
  });
  assert.equal(canonical, 'https://es.aliexpress.com/item/1005012721085216.html');
});

test('exposes the canonical URL when affiliate data contains a stale product id', async () => {
  const metadata = await resolveAliExpressAffiliateProduct('https://a.aliexpress.com/_perfume', {
    appKey: 'test-key',
    appSecret: 'test-secret',
    trackingId: 'chollosaldia88id',
  }, {
    resolveShortUrl: async () => 'https://es.aliexpress.com/item/1005012721085216.html',
    fetchImpl: async () => ({
      json: async () => ({
        aliexpress_affiliate_product_query_response: { resp_result: { result: { products: { product: [{
          product_id: '1005012646899284',
          product_title: 'Respuesta antigua de catálogo',
          target_sale_price: '19.99',
          promotion_link: 'https://s.click.aliexpress.com/e/_propio',
        }] } } } },
      }),
    }),
  });
  assert.equal(metadata.canonicalUrl, 'https://es.aliexpress.com/item/1005012721085216.html');
  assert.equal(metadata.productId, '1005012646899284');
});
